version: 2.1

orbs:
  ci: skedulo/ci@0.5.4

electron: &electron
  resource_class: medium
  environment:
    TZ: "/usr/share/zoneinfo/Australia/Brisbane"
  docker:
    - image: electronuserland/builder:wine

defaults: &defaults
  docker:
    - image: cimg/node:10.24.1
  environment:
    TZ: "/usr/share/zoneinfo/Australia/Brisbane"
  resource_class: medium

commands:
  build-sdk:
    description: Bootstrap, Test and Compile Custom Page SDK
    steps:
      # Restore Custom Page node_modules
      - restore_cache:
          key: yarn-cache-v2-{{ checksum "yarn.lock" }}-{{ checksum "src/yarn.lock" }}

      - run:
          command: |
            yarn bootstrap

      - save_cache:
          key: yarn-cache-v2-{{ checksum "yarn.lock" }}-{{ checksum "src/yarn.lock" }}
          paths:
            - node_modules
            - src/node_modules

      - run:
          command: |
            yarn electron-builder install-app-deps
            # https://github.com/electron-userland/electron-builder/issues/3179
            USE_HARD_LINKS=false yarn electron-builder -wml

  authenticate-with-npm:
    steps:
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

jobs:
  build-custom-page-sdk:
    <<: *electron

    steps:
      - checkout
      - authenticate-with-npm
      - build-sdk
      - persist_to_workspace:
          root: ./
          paths:
            - ./dist

  deploy-sdk-to-s3:
    <<: *defaults

    parameters:
      deploy_type:
        type: string

    steps:
      - checkout
      - when:
        # Auth to Core-Test by default
          condition:
              not:
                matches:
                  pattern: "^master$"
                  value: << pipeline.git.branch >>
          steps:
              - ci/aws_assume_role:
                  aws_role_arn: arn:aws:iam::208503650764:role/circle_ci_update_sdks

      - when:
         # If this branch is master, auth to Core-Prod instead
          condition:
              matches:
                  pattern: "^master$"
                  value: << pipeline.git.branch >>
          steps:
              - ci/aws_assume_role:
                  aws_role_arn: arn:aws:iam::133580534388:role/circle_ci_update_sdks
      - attach_workspace:
          at: ./
      - run: ~/project/tools/evaluate-sdk-deploy.sh << parameters.deploy_type >> $CIRCLE_BRANCH ~/project/dist ~/project/tools

workflows:
  everything:
    jobs:
      - build-custom-page-sdk:
          context: npm_skeddevenv_read_only

      - deploy-sdk-to-s3:
          name: deploy-latest-file
          deploy_type: "latest"
          requires:
            - build-custom-page-sdk
          filters:
            branches:
              only:
                  - master
                  - dev
          context: aws_blank_oidc_context

      - deploy-sdk-to-s3:
          name: deploy-release-file
          deploy_type: "release"
          requires:
            - build-custom-page-sdk
          filters:
            branches:
              only:
                  - master
          context: aws_blank_oidc_context

      - deploy-sdk-to-s3:
          name: deploy-branch-file
          deploy_type: "branch"
          requires:
            - build-custom-page-sdk
          filters:
            branches:
              ignore:
                  - master
                  - dev
          context: aws_blank_oidc_context
